spring.application.name=EurekaServer
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Human-readable log format for the dashboard
eureka.server.wait-time-in-ms-when-sync-empty=0